#!/bin/bash

# Exit on error
set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
FWPATH="Embedded/RC_Controller"

cd $DIR
cd $FWPATH

# Build all FWs
make -j4 drangen
make -j4 mactrac

mv build/fw_*.bin precompiled/.
