#!/bin/bash

# http://stackoverflow.com/questions/14170590/building-qt-5-on-linux-for-windows

# cd /opt
# sudo mkdir mxe
# sudo chown $USER mxe
# git clone https://github.com/mxe/mxe.git
# sudo apt-get install autoconf automake autopoint bash bison bzip2 flex gettext git g++ gperf intltool libffi-dev libgdk-pixbuf2.0-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl p7zip-full patch perl pkg-config python ruby scons sed unzip wget xz-utils g++-multilib libc6-dev-i386
# cd mxe
# make qtbase
# make qtserialport

#
# Fixes
#
# When compiling qt - make gdal_CONFIGURE_OPTS='--with-openjpeg=no --with-cryptopp=no' EXCLUDE_PKGS='ocaml%'
# When compiling program - in the makefile change -lopengl32 to /opt/mxe/usr/i686-w64-mingw32.static/lib/libopengl32.a


export PATH=/opt/mxe/usr/bin/:$PATH
#/opt/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5 -config release "CONFIG+=release_win"
/opt/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5
make clean
make -j8
rm -rf build/win/obj

